<?php
/**
 * @file
 * Code for the Domains feature.
 */

/**
 * Implements MODULE_preprocess_menu_link().
 */
function mda_domains_preprocess_menu_link(&$variables) {
	if (substr($variables['element']['#href'],0,4) == 'http') {
		$current_domain = domain_get_domain();
		$domain_parts = explode('.mda34.', $current_domain['subdomain']);
		if ($domain_parts[1] != 'org') {
			$variables['element']['#href'] = str_replace('org', $domain_parts[1], $variables['element']['#href']);
		}
	}
}

/**
 * Helper function
 *
 * @return string Domain suffix (ex: .org, .dev, .korora.fr, ...)
 */
function mda_domain_suffix() {
  $current_domain = domain_get_domain();
  $parts = explode('mda34', $current_domain['subdomain']);
  return $parts[1];
}