<?php
/**
 * @file
 * mda_structures.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mda_structures_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Médiation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '00a0cfef-0747-4d69-be4c-7ffbfdb2d01e',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Interventions cadre scolaire',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0c6d5057-7541-453a-8e68-277f98d47b14',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Médiation scolaire',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1055cebb-f4c0-4be9-bc60-335768afe3fa',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Culturel',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '138c4691-c5d6-4982-ab5e-cbd4cea99368',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Juridique',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1d8e7a37-6f79-471b-b3ce-3cb8a2e38490',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Accueil',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1faf4b3c-1e32-47d0-8476-18cdce183a40',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Social',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2d2bfd20-454a-4724-b500-4fc96c670cc2',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Activités/ Séjours',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '35ad89b6-8464-4fe1-99ce-4c268cdf165f',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Médiation sociale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '46a0a35c-c53d-4c3d-901f-3c58a027f666',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Environnement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4a5b63e9-9f94-4fde-98b2-47b88c43867b',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Etablissement public',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4cabbc6c-6c41-49b0-8697-77cff02358ee',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Interventions cadre extra-scolaire',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '57e03cd7-09f4-41e0-acce-63e5074d14de',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Educatif',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5954b0e4-e20f-4c6b-8ea1-0e6b1b917686',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Groupement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '59ee0a27-b62c-41fd-ae01-463fdd6e8a3f',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Prise en charge',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '67c0c460-8bef-4d9d-984b-4241acdae095',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Consultation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '73479b75-7301-4b69-963b-b2091abc0d9b',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Insertion',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '73d00ac0-071e-4910-a422-38d3d14b3ed3',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Animation familiale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7637f287-a204-4491-9d70-dc80976e86e3',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Soutien scolaire',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '7de234bb-4b8c-4a97-9c83-c60371a5953f',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Soin et accompagnement individuel',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8a00af2c-ce4e-4fbd-90e8-0fa0b0f99cfa',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Écoute',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8c94649e-0bea-4559-8ed0-96583e93c299',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Ateliers collectifs',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '954beba7-26a0-48fd-95e8-8b09db7219f9',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Médiation culturelle',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a0d628ef-6d83-4ef9-be9a-8d538dd8ce46',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sportif',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'aea8aff6-c27f-4505-9282-e8544c5eca3b',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Fondation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'be73407d-00ec-40af-a983-0bda8899a3e4',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Action de prévention',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c8938348-4dc6-4601-a914-a3702f538bfe',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Conseil',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'cdb50982-0cfe-4fb2-963c-2273544a2b11',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Collectivité locale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd0250c8f-545d-4d7b-873d-486cb84590ae',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Orientation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd486f36e-8931-401e-b09b-e4b44e726ddf',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Médiation familiale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'd912f1d5-cbb6-4f42-9b3b-437423f457e0',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Information',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e3aeb647-472d-46e6-9430-ec1515dfa2ac',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Médical / Médico-social',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e3fb5509-aff0-4af5-aa09-e2e31f4bb62c',
    'vocabulary_machine_name' => 'competence_fields',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Soutien à la parentalité',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e5f13504-5b3b-4938-a456-c042b939cd2d',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Animation collective',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'eba30b80-d0ae-4cf1-ad4e-6d5eeb3c956e',
    'vocabulary_machine_name' => 'action_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Société',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f337d14e-9751-4f21-afaa-0866972d9141',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Association',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f5c5cf8e-915b-4d18-8f45-6ec822356a1f',
    'vocabulary_machine_name' => 'structure_types',
    'metatags' => array(),
  );
  return $terms;
}
