<?php
/**
 * @file
 * mda_faqs.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mda_faqs_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Secte',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0617cd7e-4a2d-427f-bc42-85a7d013e420',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Violence',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '068dc05e-4394-4fad-bb52-c8fd4b9312cb',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Addictions',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '14bc967b-2d2f-415a-9189-2b4e53ec3f8b',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Santé mentale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1cd0fb9d-76db-4df4-b31e-41340990d0ee',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Politique santé',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '266a2490-e25f-4e8e-9531-0025d3baa412',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Grossesse adolescente',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2774108a-148e-4c28-bf05-84d4a4cb58e4',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Education parentale',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3463c00f-d3e0-4369-8873-8ee4af0abae4',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Thématiques',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Errance',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3c5bde90-73ce-4195-b5cb-4080eef43dd8',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Sexualité',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5b84bf65-bcad-4247-8eb3-2e3bc4898b23',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Temps personnel',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '67c77ff2-467d-4e4a-a5b0-ecf5113a2193',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Descolarisation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '87d1f4b7-2d5a-4487-a93b-64a271771228',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Contraception',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8de5bdd6-e549-4588-9e58-bc46dba44dbb',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Adolescence',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'aba13c94-47a2-4fad-b8f3-7358961ded40',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Relation famille - institution',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ad359fd4-4512-4210-b10d-cc40b63729ca',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'MDA',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b5d2a01d-2f3e-4928-ac4b-f510f0b61a91',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Délinquance',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b82bbcd8-5eae-4b27-9d92-c66a027266fc',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Enquêtes santé',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'be7e0cd1-a1eb-4e07-acfd-2d8892c4c710',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  $terms[] = array(
    'name' => 'Inceste',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c423a4e3-c980-4ae9-9374-3ab6867f18f7',
    'vocabulary_machine_name' => 'faq_categories',
    'metatags' => array(),
    'parent' => array(
      0 => '3aa56d45-2dd4-4ec1-a65f-36e345030e4b',
    ),
  );
  return $terms;
}
