<?php
/**
 * @file
 * mda_events.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function mda_events_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Adolescents',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '007c141b-e214-4ee1-851e-391aa8050ee8',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Festival',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '041ab6a4-7227-4475-a1f4-afb66a336e75',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Projection',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '069e2b8a-0306-4ad7-9249-6288a2cf0dd1',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Atelier',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '10d305b7-9eb3-41a2-8152-6f277a9cb2a2',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Famille',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '1af2b068-c81c-40db-a455-ce89a902b3e4',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Animation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '23b13655-a969-4664-b5b3-4bb591d3a3e1',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Professionnels  de l\'animation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2ee9b115-732e-4e1f-89d2-00810314b89c',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Représentation culturelle',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '395c6235-7c3a-4ac0-b2c4-10201c73d81b',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Professionnels  de l\'écoute et de l\'accompagnement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3a4d4b8d-d1f0-4bdb-a47d-f1bbd3b15454',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Professionnels  de l\'éducation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '47617470-634a-4105-8222-79516d782092',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Hapenning',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '51eecc51-bb3e-461d-9c91-cfc36dbbe4fe',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Spectacle',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '56b96e4b-c085-4379-9a72-373d8cb5f416',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Parents',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '59aec64b-acfe-485f-8e35-0ebf1ded860f',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Table ronde',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5a36469b-c9cf-4388-a31b-9baa5282581e',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Exposition',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '6dd7a8c9-9cf4-403e-94e2-1c2de38f55e2',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Professionnels  du social',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '82d67b41-2a5f-4479-a958-4978c4f230b3',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Professionnels de santé',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '82eb57df-5795-4390-bcff-d7596e42e807',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Conférence',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '873d205f-858b-428f-bcc3-30d7cd70c178',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Représentation artistique',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9bd3f994-b571-4591-83d8-9591fe125b44',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Groupe de parole',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ad83b0cc-5f1c-4f7e-88af-99d7b8fe7efd',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Formation',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'b56b05a2-2bae-48fe-8f6f-4d67fe92dadc',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Séminaire',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'bdd2bc8c-1016-4f39-a7f1-fa58e8e85cef',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Réunion',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'be6e6db1-978a-4963-8f68-e6515049fe33',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Tout public',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'c1f36c68-37e9-4aea-99ba-7f373e028161',
    'vocabulary_machine_name' => 'publics',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Colloque',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'de973aaa-74de-4556-a47d-0a9d4a8550df',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Sortie',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f76c0dd3-b3d8-49f8-bb9e-bc9cd291c4d6',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Rencontre',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'f9acd689-992c-4089-b9da-cb2333036284',
    'vocabulary_machine_name' => 'event_types',
    'metatags' => array(),
  );
  return $terms;
}
